// This file is auto-generated by @hey-api/openapi-ts

export const AnalyticsChartDataSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        visits: {
            type: 'integer',
            title: 'Visits'
        }
    },
    type: 'object',
    required: ['date', 'visits'],
    title: 'AnalyticsChartData'
} as const;

export const AnalyticsDashboardSchema = {
    properties: {
        stats: {
            '$ref': '#/components/schemas/AnalyticsStats'
        },
        chart_data: {
            items: {
                '$ref': '#/components/schemas/AnalyticsChartData'
            },
            type: 'array',
            title: 'Chart Data'
        }
    },
    type: 'object',
    required: ['stats', 'chart_data'],
    title: 'AnalyticsDashboard'
} as const;

export const AnalyticsStatsSchema = {
    properties: {
        total_users: {
            type: 'integer',
            title: 'Total Users'
        },
        total_visitors: {
            type: 'integer',
            title: 'Total Visitors'
        },
        total_visits: {
            type: 'integer',
            title: 'Total Visits'
        },
        visits_today: {
            type: 'integer',
            title: 'Visits Today'
        }
    },
    type: 'object',
    required: ['total_users', 'total_visitors', 'total_visits', 'visits_today'],
    title: 'AnalyticsStats'
} as const;

export const Body_knowledge_upload_knowledge_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_knowledge-upload_knowledge_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatMessageSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['role', 'content'],
    title: 'ChatMessage',
    description: 'Định nghĩa cấu trúc một tin nhắn trong hội thoại.'
} as const;

export const ChatRequestSchema = {
    properties: {
        messages: {
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            type: 'array',
            title: 'Messages'
        }
    },
    type: 'object',
    required: ['messages'],
    title: 'ChatRequest',
    description: 'Request gửi lên từ Frontend chứa danh sách tin nhắn.'
} as const;

export const ChatResponseSchema = {
    properties: {
        reply: {
            type: 'string',
            title: 'Reply'
        }
    },
    type: 'object',
    required: ['reply'],
    title: 'ChatResponse',
    description: 'Phản hồi trả về cho Frontend (Dạng không stream).'
} as const;

export const CypherQuerySchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        }
    },
    type: 'object',
    required: ['query'],
    title: 'CypherQuery'
} as const;

export const CypherResultSchema = {
    properties: {
        data: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Data'
        },
        columns: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Columns'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'CypherResult'
} as const;

export const GraphDataSchema = {
    properties: {
        nodes: {
            items: {
                '$ref': '#/components/schemas/GraphNode'
            },
            type: 'array',
            title: 'Nodes'
        },
        links: {
            items: {
                '$ref': '#/components/schemas/GraphRelationship'
            },
            type: 'array',
            title: 'Links'
        }
    },
    type: 'object',
    required: ['nodes', 'links'],
    title: 'GraphData'
} as const;

export const GraphNodeSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Id'
        },
        labels: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Labels'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['id', 'labels', 'properties'],
    title: 'GraphNode'
} as const;

export const GraphRelationshipSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Id'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Source'
        },
        target: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Target'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['id', 'source', 'target', 'type', 'properties'],
    title: 'GraphRelationship'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        neo4j: {
            type: 'string',
            title: 'Neo4J'
        },
        cache: {
            additionalProperties: true,
            type: 'object',
            title: 'Cache'
        }
    },
    type: 'object',
    required: ['status', 'neo4j', 'cache'],
    title: 'HealthResponse',
    description: 'Thông tin về tình trạng hoạt động của hệ thống.'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const KnowledgeStatsSchema = {
    properties: {
        neo4j_status: {
            type: 'string',
            title: 'Neo4J Status'
        },
        total_nodes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Nodes'
        },
        total_relationships: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Relationships'
        }
    },
    type: 'object',
    required: ['neo4j_status'],
    title: 'KnowledgeStats'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VisitEventPublicSchema = {
    properties: {
        path: {
            type: 'string',
            maxLength: 512,
            title: 'Path'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        visitor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Visitor Id'
        },
        timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['path', 'id', 'visitor_id'],
    title: 'VisitEventPublic'
} as const;

export const VisitEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VisitEventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'VisitEventsPublic'
} as const;

export const VisitorPublicSchema = {
    properties: {
        ip_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 45
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        user_agent: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Agent'
        },
        device: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device'
        },
        browser: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Browser'
        },
        os: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Os'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'VisitorPublic'
} as const;