// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AnalyticsTrackVisitorData, AnalyticsTrackVisitorResponse, AnalyticsGetAnalyticsStatsResponse, AnalyticsGetVisitEventsData, AnalyticsGetVisitEventsResponse, ChatbotChatData, ChatbotChatResponse, ChatbotChatStreamData, ChatbotChatStreamResponse, ChatbotHealthResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, KnowledgeGetKnowledgeStatsResponse, KnowledgeUploadKnowledgeDocumentData, KnowledgeUploadKnowledgeDocumentResponse, KnowledgeExecuteCypherData, KnowledgeExecuteCypherResponse, KnowledgeGetGraphDataData, KnowledgeGetGraphDataResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AnalyticsService {
    /**
     * Track Visitor
     * Theo dõi lượt truy cập. Nếu không có visitor cookie, tạo mới một visitor.
     * @param data The data for the request.
     * @param data.path
     * @returns VisitorPublic Successful Response
     * @throws ApiError
     */
    public static trackVisitor(data: AnalyticsTrackVisitorData): CancelablePromise<AnalyticsTrackVisitorResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analytics/track',
            query: {
                path: data.path
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Analytics Stats
     * Lấy thống kê tổng quan cho Dashboard. Chỉ dành cho Admin.
     * @returns AnalyticsDashboard Successful Response
     * @throws ApiError
     */
    public static getAnalyticsStats(): CancelablePromise<AnalyticsGetAnalyticsStatsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/analytics/stats'
        });
    }
    
    /**
     * Get Visit Events
     * Lấy danh sách các sự kiện truy cập.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns VisitEventsPublic Successful Response
     * @throws ApiError
     */
    public static getVisitEvents(data: AnalyticsGetVisitEventsData = {}): CancelablePromise<AnalyticsGetVisitEventsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/analytics/visitors',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ChatbotService {
    /**
     * Chat
     * Xử lý tin nhắn chat với đầy đủ lịch sử hội thoại (hỗ trợ đa lượt).
     * Đây là endpoint đồng bộ (trả về kết quả một lượt).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ChatResponse Successful Response
     * @throws ApiError
     */
    public static chat(data: ChatbotChatData): CancelablePromise<ChatbotChatResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chatbot/chat',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Chat Stream
     * Endpoint xử lý chat dạng Streaming (SSE).
     * Trả về dữ liệu theo từng từ để tạo hiệu ứng gõ chữ mượt mà cho UI.
     * Chỉ cho phép người dùng đã đăng nhập sử dụng.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static chatStream(data: ChatbotChatStreamData): CancelablePromise<ChatbotChatStreamResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chatbot/chat/stream',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health
     * Kiểm tra sức khỏe hệ thống: Kết nối Neo4j và thống kê bộ nhớ đệm.
     * @returns HealthResponse Successful Response
     * @throws ApiError
     */
    public static health(): CancelablePromise<ChatbotHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chatbot/health'
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class KnowledgeService {
    /**
     * Get Knowledge Stats
     * Lấy thông kê hệ thống Tri thức (Neo4j).
     * @returns KnowledgeStats Successful Response
     * @throws ApiError
     */
    public static getKnowledgeStats(): CancelablePromise<KnowledgeGetKnowledgeStatsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/knowledge/stats'
        });
    }
    
    /**
     * Upload Knowledge Document
     * Tải tài liệu lên để hệ thống học.
     * (API Demo - Cần tích hợp với hệ thống chia nhỏ văn bản và tạo Vector Embeddings)
     * @param data The data for the request.
     * @param data.formData
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static uploadKnowledgeDocument(data: KnowledgeUploadKnowledgeDocumentData): CancelablePromise<KnowledgeUploadKnowledgeDocumentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/knowledge/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Execute Cypher
     * Thực thi câu lệnh Cypher (Chỉ dành cho Admin).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CypherResult Successful Response
     * @throws ApiError
     */
    public static executeCypher(data: KnowledgeExecuteCypherData): CancelablePromise<KnowledgeExecuteCypherResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/knowledge/cypher',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Graph Data
     * Lấy dữ liệu đồ thị (nodes và relationships) để hiển thị.
     * @param data The data for the request.
     * @param data.limit
     * @returns GraphData Successful Response
     * @throws ApiError
     */
    public static getGraphData(data: KnowledgeGetGraphDataData = {}): CancelablePromise<KnowledgeGetGraphDataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/knowledge/graph',
            query: {
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * Đăng nhập bằng OAuth2 tương thích, lấy Access Token cho các yêu cầu sau này.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Kiểm tra tính hợp lệ của Access Token hiện tại.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Yêu cầu phục hồi mật khẩu qua Email.
     * Hệ thống sẽ tạo mật khẩu mới và gửi về email.
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Đặt lại mật khẩu mới bằng Token đã nhận được từ email.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * Lấy nội dung HTML của email phục hồi mật khẩu (Chỉ dành cho Admin).
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Lấy danh sách người dùng (Chỉ dành cho Admin).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Tạo người dùng mới (Chỉ dành cho Admin).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Lấy thông tin của người dùng hiện tại đang đăng nhập.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Tự xóa tài khoản của chính mình.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Cập nhật thông tin cá nhân của người dùng đang đăng nhập.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Cập nhật mật khẩu cá nhân.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Đăng ký tài khoản mới (Công khai).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Lấy thông tin người dùng cụ thể theo ID.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Cập nhật thông tin người dùng bất kỳ (Chỉ dành cho Admin).
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Xóa một người dùng (Chỉ dành cho Admin).
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}