// This file is auto-generated by @hey-api/openapi-ts

export type AnalyticsChartData = {
    date: string;
    visits: number;
};

export type AnalyticsDashboard = {
    stats: AnalyticsStats;
    chart_data: Array<AnalyticsChartData>;
};

export type AnalyticsStats = {
    total_users: number;
    total_visitors: number;
    total_visits: number;
    visits_today: number;
};

export type Body_knowledge_upload_knowledge_document = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Định nghĩa cấu trúc một tin nhắn trong hội thoại.
 */
export type ChatMessage = {
    role: string;
    content: string;
};

/**
 * Request gửi lên từ Frontend chứa danh sách tin nhắn.
 */
export type ChatRequest = {
    messages: Array<ChatMessage>;
};

/**
 * Phản hồi trả về cho Frontend (Dạng không stream).
 */
export type ChatResponse = {
    reply: string;
};

export type CypherQuery = {
    query: string;
};

export type CypherResult = {
    data: Array<{
        [key: string]: unknown;
    }>;
    columns?: (Array<(string)> | null);
};

export type GraphData = {
    nodes: Array<GraphNode>;
    links: Array<GraphRelationship>;
};

export type GraphNode = {
    id: (string | number);
    labels: Array<(string)>;
    properties: {
        [key: string]: unknown;
    };
};

export type GraphRelationship = {
    id: (string | number);
    source: (string | number);
    target: (string | number);
    type: string;
    properties: {
        [key: string]: unknown;
    };
};

/**
 * Thông tin về tình trạng hoạt động của hệ thống.
 */
export type HealthResponse = {
    status: string;
    neo4j: string;
    cache: {
        [key: string]: unknown;
    };
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KnowledgeStats = {
    neo4j_status: string;
    total_nodes?: (number | null);
    total_relationships?: (number | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VisitEventPublic = {
    path: string;
    id: string;
    visitor_id: string;
    timestamp?: (string | null);
};

export type VisitEventsPublic = {
    data: Array<VisitEventPublic>;
    count: number;
};

export type VisitorPublic = {
    ip_address?: (string | null);
    user_agent?: (string | null);
    device?: (string | null);
    browser?: (string | null);
    os?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type AnalyticsTrackVisitorData = {
    path: string;
};

export type AnalyticsTrackVisitorResponse = (VisitorPublic);

export type AnalyticsGetAnalyticsStatsResponse = (AnalyticsDashboard);

export type AnalyticsGetVisitEventsData = {
    limit?: number;
    skip?: number;
};

export type AnalyticsGetVisitEventsResponse = (VisitEventsPublic);

export type ChatbotChatData = {
    requestBody: ChatRequest;
};

export type ChatbotChatResponse = (ChatResponse);

export type ChatbotChatStreamData = {
    requestBody: ChatRequest;
};

export type ChatbotChatStreamResponse = (unknown);

export type ChatbotHealthResponse = (HealthResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type KnowledgeGetKnowledgeStatsResponse = (KnowledgeStats);

export type KnowledgeUploadKnowledgeDocumentData = {
    formData: Body_knowledge_upload_knowledge_document;
};

export type KnowledgeUploadKnowledgeDocumentResponse = (Message);

export type KnowledgeExecuteCypherData = {
    requestBody: CypherQuery;
};

export type KnowledgeExecuteCypherResponse = (CypherResult);

export type KnowledgeGetGraphDataData = {
    limit?: number;
};

export type KnowledgeGetGraphDataResponse = (GraphData);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);