"""Add visitor and analytics models

Revision ID: 967951d30832
Revises: fe56fa70289e
Create Date: 2026-05-26 23:11:45.237347

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '967951d30832'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitevent',
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('visitor_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitevent')
    op.drop_table('visitor')
    # ### end Alembic commands ###
